export const productsList = [
  {
    group: "Waffles",
    name: "Waffles Extraordinaire",
    price: 10,
    image: "waffles_extraordinaire",
    desc: "Extraordinarily Delicious and Scrumptious!",
  },
  {
    group: "Waffles",
    name: "Waffles Delight",
    price: 12,
    image: "waffles_delight",
    desc: "Delightfully Pleasant and tasty!",
  },
  {
    group: "Waffles",
    name: "Waffles Supreme",
    price: 15,
    image: "waffles_supreme",
    desc: "Supreme Meal for Winners!!",
  },
  {
    group: "Waffles",
    name: "Waffles Classic",
    price: 8,
    image: "waffles_classic",
    desc: "Classic and Can't be Beat!!",
  },
  {
    group: "Waffles",
    name: "Waffles Extraordinaire",
    price: 10,
    image: "waffles_extraordinaire",
    desc: "Extraordinarily Delicious and Scrumptious!",
  },
  {
    group: "Waffles",
    name: "Waffles Delight",
    price: 12,
    image: "waffles_delight",
    desc: "Delightfully Pleasant and tasty!",
  },
  {
    group: "Waffles",
    name: "Waffles Supreme",
    price: 15,
    image: "waffles_supreme",
    desc: "Supreme Meal for Winners!!",
  },
  {
    group: "Waffles",
    name: "Waffles Classic",
    price: 8,
    image: "waffles_classic",
    desc: "Classic and Can't be Beat!!",
  },
  {
    group: "Waffles",
    name: "Waffles Extraordinaire",
    price: 10,
    image: "waffles_extraordinaire",
    desc: "Extraordinarily Delicious and Scrumptious!",
  },
  {
    group: "Waffles",
    name: "Waffles Delight",
    price: 12,
    image: "waffles_delight",
    desc: "Delightfully Pleasant and tasty!",
  },
  {
    group: "Waffles",
    name: "Waffles Supreme",
    price: 15,
    image: "waffles_supreme",
    desc: "Supreme Meal for Winners!!",
  },
  {
    group: "Waffles",
    name: "Waffles Classic",
    price: 8,
    image: "waffles_classic",
    desc: "Classic and Can't be Beat!!",
  },
  {
    group: "Waffles",
    name: "Waffles Extraordinaire",
    price: 10,
    image: "waffles_extraordinaire",
    desc: "Extraordinarily Delicious and Scrumptious!",
  },
  {
    group: "Waffles",
    name: "Waffles Delight",
    price: 12,
    image: "waffles_delight",
    desc: "Delightfully Pleasant and tasty!",
  },
  {
    group: "Waffles",
    name: "Waffles Supreme",
    price: 15,
    image: "waffles_supreme",
    desc: "Supreme Meal for Winners!!",
  },
  {
    group: "Waffles",
    name: "Waffles Classic",
    price: 8,
    image: "waffles_classic",
    desc: "Classic and Can't be Beat!!",
  },
  {
    group: "Waffles",
    name: "Waffles Extraordinaire",
    price: 10,
    image: "waffles_extraordinaire",
    desc: "Extraordinarily Delicious and Scrumptious!",
  },
  {
    group: "Waffles",
    name: "Waffles Delight",
    price: 12,
    image: "waffles_delight",
    desc: "Delightfully Pleasant and tasty!",
  },
  {
    group: "Waffles",
    name: "Waffles Supreme",
    price: 15,
    image: "waffles_supreme",
    desc: "Supreme Meal for Winners!!",
  },
  {
    group: "Waffles",
    name: "Waffles Classic",
    price: 8,
    image: "waffles_classic",
    desc: "Classic and Can't be Beat!!",
  },
  {
    group: "Waffles",
    name: "Waffles Extraordinaire",
    price: 10,
    image: "waffles_extraordinaire",
    desc: "Extraordinarily Delicious and Scrumptious!",
  },
  {
    group: "Waffles",
    name: "Waffles Delight",
    price: 12,
    image: "waffles_delight",
    desc: "Delightfully Pleasant and tasty!",
  },
  {
    group: "Waffles",
    name: "Waffles Supreme",
    price: 15,
    image: "waffles_supreme",
    desc: "Supreme Meal for Winners!!",
  },
  {
    group: "Waffles",
    name: "Waffles Classic",
    price: 8,
    image: "waffles_classic",
    desc: "Classic and Can't be Beat!!",
  },
].map((product, index) => ({ ...product, id: index + 1 }));

export const newProducts = [
  {
    group: "Waffles",
    name: "Waffles Extraordinaire",
    price: 10,
    image: "waffles_extraordinaire",
    desc: "Extraordinarily Delicious and Scrumptious!",
  },
  {
    group: "Waffles",
    name: "Waffles Delight",
    price: 12,
    image: "waffles_delight",
    desc: "Delightfully Pleasant and tasty!",
  },
  {
    group: "Waffles",
    name: "Waffles Supreme",
    price: 15,
    image: "waffles_supreme",
    desc: "Supreme Meal for Winners!!",
  },
  {
    group: "Waffles",
    name: "Waffles Classic",
    price: 8,
    image: "waffles_classic",
    desc: "Classic and Can't be Beat!!",
  },
  {
    group: "Waffles",
    name: "Waffles Extraordinaire",
    price: 10,
    image: "waffles_extraordinaire",
    desc: "Extraordinarily Delicious and Scrumptious!",
  },
  {
    group: "Waffles",
    name: "Waffles Delight",
    price: 12,
    image: "waffles_delight",
    desc: "Delightfully Pleasant and tasty!",
  },
  {
    group: "Waffles",
    name: "Waffles Supreme",
    price: 15,
    image: "waffles_supreme",
    desc: "Supreme Meal for Winners!!",
  },
  {
    group: "Waffles",
    name: "Waffles Classic",
    price: 8,
    image: "waffles_classic",
    desc: "Classic and Can't be Beat!!",
  },
  {
    group: "Waffles",
    name: "Waffles Extraordinaire",
    price: 10,
    image: "waffles_extraordinaire",
    desc: "Extraordinarily Delicious and Scrumptious!",
  },
  {
    group: "Waffles",
    name: "Waffles Delight",
    price: 12,
    image: "waffles_delight",
    desc: "Delightfully Pleasant and tasty!",
  },
  {
    group: "Waffles",
    name: "Waffles Supreme",
    price: 15,
    image: "waffles_supreme",
    desc: "Supreme Meal for Winners!!",
  },
  {
    group: "Waffles",
    name: "Waffles Classic",
    price: 8,
    image: "waffles_classic",
    desc: "Classic and Can't be Beat!!",
  },
  {
    group: "Waffles",
    name: "Waffles Extraordinaire",
    price: 10,
    image: "waffles_extraordinaire",
    desc: "Extraordinarily Delicious and Scrumptious!",
  },
  {
    group: "Waffles",
    name: "Waffles Delight",
    price: 12,
    image: "waffles_delight",
    desc: "Delightfully Pleasant and tasty!",
  },
  {
    group: "Waffles",
    name: "Waffles Supreme",
    price: 15,
    image: "waffles_supreme",
    desc: "Supreme Meal for Winners!!",
  },
  {
    group: "Waffles",
    name: "Waffles Classic",
    price: 8,
    image: "waffles_classic",
    desc: "Classic and Can't be Beat!!",
  },
  {
    group: "Waffles",
    name: "Waffles Extraordinaire",
    price: 10,
    image: "waffles_extraordinaire",
    desc: "Extraordinarily Delicious and Scrumptious!",
  },
  {
    group: "Waffles",
    name: "Waffles Delight",
    price: 12,
    image: "waffles_delight",
    desc: "Delightfully Pleasant and tasty!",
  },
  {
    group: "Waffles",
    name: "Waffles Supreme",
    price: 15,
    image: "waffles_supreme",
    desc: "Supreme Meal for Winners!!",
  },
  {
    group: "Waffles",
    name: "Waffles Classic",
    price: 8,
    image: "waffles_classic",
    desc: "Classic and Can't be Beat!!",
  },
  {
    group: "Waffles",
    name: "Waffles Extraordinaire",
    price: 10,
    image: "waffles_extraordinaire",
    desc: "Extraordinarily Delicious and Scrumptious!",
  },
  {
    group: "Waffles",
    name: "Waffles Delight",
    price: 12,
    image: "waffles_delight",
    desc: "Delightfully Pleasant and tasty!",
  },
  {
    group: "Waffles",
    name: "Waffles Supreme",
    price: 15,
    image: "waffles_supreme",
    desc: "Supreme Meal for Winners!!",
  },
  {
    group: "Waffles",
    name: "Waffles Classic",
    price: 8,
    image: "waffles_classic",
    desc: "Classic and Can't be Beat!!",
  },
].map((product, index) => ({ ...product, id: index + 30 }));
